### ISSUE TITLE
Backend: Discussion

### ISSUE THREAD

**Issue by jnv27** [Girl-Code-It/Opportunity-Calendar-Backend#1]
Hello @Manvityagi ,
I would like to contribute on backend part of this project as part of GSSOC'21 programme. Willing to discuss more about this project. Add me to relevant group or discord channel whenever it will be created.

**Comment by Manvityagi** [comment]
Hi,
Are you a gssoc participant?

**Comment by jnv27** [comment]
Yes @Manvityagi I'm a Gssoc participant.

**Comment by Manvityagi** [comment]
In a couple of days or so, you will be able to see all the project channels
on the GirlScript Discord server,
then you can join #opportunity-calendar-backend.

**Comment by jnv27** [comment]
Alright, but till then can I start contributing to this project or it will only start after joining discord channel?

**Comment by rohithmsr** [comment]
Where is the channel?

**Comment by Manvityagi** [comment]
Let me discuss with the other mentors, 
What can we do. 

Cc: @abdus

**Comment by abdus** [comment]
@jnv27 hey. we have a channel for this project on the GirlScript SoC discord server. Channel's name is `#opportunity-calendar-backend`. However, I think it would be better if you discuss it in this thread (you are free to discuss it on Discord as well)

So, about the backend: We are planning to have an [Express](https://expressjs.com/) server running. For the database, we can use MongoDB. I was thinking of going with TypeScript for the backend. My reasoning behind using TypeScript is, it introduces a type system to JavaScript..which in turn, makes a collaborative project easily maintainable. 

I am open to suggestions.

cc: @Manvityagi

**Comment by jnv27** [comment]
Hi @abdus , I have previously worked with Express and MongoDB both so i would suggest the same, but i don't have much idea about TypeScript, as I have worked previously with JavaScript only. But i would love to know more about TypeScript if it is mandatory for this project.

**Comment by abdus** [comment]
@jnv27 well ... it's not mandatory, just preferred.

**Comment by Athira2199** [comment]
Hi @abdus @Manvityagi would love to contribute in the project.

**Comment by jnv27** [comment]
@abdus Alright, but can we initially start with normal javascript and later on we can shift to Typescript if it's possible?

**Comment by rohithmsr** [comment]
@abdus I am ok with using Typescript. Though I have no experience in Typescript, according to me, contributors can take this opportunity to gain knowledge on Typescript.

**Comment by abdus** [comment]
We will start with TypeScript. I will create an issue for the initial project set-up.

**Comment by rohithmsr** [comment]
Since the frontend and backend are seperate projects, how will we be able to know what are all the features in the website? This question may be absurd but I really have no clue on working on medium level projects

@abdus

**Comment by abdus** [comment]
@rohithmsr For now, we need to create endpoints for adding and editing opportunities. Then there is the authentication mechanism.
We will be adding new features as the need arises.

**Comment by Manvityagi** [comment]
Hi @jnv27 @rohithmsr @Athira2199, The project has been restarted from scratch, we shifted to NodeJS from Django, 
You may check the open issues.

**Comment by Manvityagi** [comment]
> Since the frontend and backend are seperate projects, how will we be able to know what are all the features in the website? This question may be absurd but I really have no clue on working on medium level projects
> 
> @abdus

You can check the Frontend Repo if you want to, or you can also check the exiting fronted deployed [here](https://happy-shockley-488e36.netlify.app/) @rohithmsr
