### ISSUE TITLE
Create the GET Opportunities API

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#16]
1. Do the required documentation change [here](https://github.com/Girl-Code-It/Opportunity-Calendar-Backend/blob/develop/documentation/APIS.md)
2. The GET API should be divided into the controllers, services, and managers as per the convention (can lookup the POST API for reference), Refer [Project Structure](https://github.com/Girl-Code-It/Opportunity-Calendar-Backend#project-structure) to know the significance of controllers, managers, services. 
3. The endpoint should be /opportunities?type=JOB 
The entries should be returned as per the query param `type` 
The 6 possible values if `type` query param are -   
       'HACKATHON',
      'JOB',
      'INTERNSHIP',
      'SCHOLARSHIP',
      'CONFERENCE',
      'CODINGCOMPETITION',

**Comment by rohithmsr** [comment]
Entire Project has been shifted to Django right?? So what should I do, jus create CRUD for opportunities right?
@Manvityagi

**Comment by Manvityagi** [comment]
> Entire Project has been shifted to Django right?? So what should I do, jus create CRUD for opportunities right?
> @Manvityagi

The project has been shifted to NodeJS already. 
The POST API needs to be made in NODEJS in current code itself

**Comment by rohithmsr** [comment]
Oh sorry! I took it other way around. I have basic knowledge on Node n Express. So shall I take this issue?
@Manvityagi

**Comment by rohithmsr** [comment]
@Manvityagi ,
when I see your code, already method for creating a new opportunity has been created right? What am I supposed to do for this issue?

**Comment by Manvityagi** [comment]
> @Manvityagi ,
> when I see your code, already method for creating a new opportunity has been created right? What am I supposed to do for this issue?

I have updated the issue, I forgot that I made the POST API already 😅

**Comment by Manvityagi** [comment]
> 1. Do the required documentation change [here](https://github.com/Girl-Code-It/Opportunity-Calendar-Backend/blob/develop/documentation/APIS.md)
> 2. The GET API should be divided into the controllers, services, and managers as per the convention (can lookup the POST API for reference), Refer [Project Structure](https://github.com/Girl-Code-It/Opportunity-Calendar-Backend#project-structure) to know the significance of controllers, managers, services.
> 3. The endpoint should be /opportunities?type=JOB
>    The entries should be returned as per the query param `type`
>    The 6 possible values , `type` query param can have -
>    'HACKATHON',
>    'JOB',
>    'INTERNSHIP',
>    'SCHOLARSHIP',
>    'CONFERENCE',
>    'CODINGCOMPETITION',

**Comment by rohithmsr** [comment]
@Manvityagi @abdus  added PR. Do you have any demo data for opportunities, if you have please add that in the repo
