### ISSUE TITLE
Change require to import

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#17]
Replace `require` with ES6 import at all places.

**Comment by Athira2199** [comment]
Would like to take up this issue, I am a GSSOC participant, please assign it to me. @Manvityagi

**Comment by Manvityagi** [comment]
> Would like to take up this issue, I am a GSSOC participant, please assign it to me. @Manvityagi

Assigned to you @Athira2199

**Comment by Manvityagi** [comment]
Hi @Athira2199 What's the progress on issue?

**Comment by Athira2199** [comment]
Hi @Manvityagi I am currently having my college exams. Please provide me a bit of more time. Will complete it soon.

**Comment by RituCs** [comment]
Hello , I would like to contribute on this issue.If no one is working on this issue then please assign it to me.Thanks !

**Comment by Athira2199** [comment]
Hi @RituCs I won't be able to look into this issue for a week. So maybe you could take it up. @Manvityagi Please do the needful changes.

**Comment by Manvityagi** [comment]
> Hello , I would like to contribute on this issue.If no one is working on this issue then please assign it to me.Thanks !

Assigned to you @RituCs. Go ahead for a PR.

**Comment by RituCs** [comment]
Please review the PR when you will get time @Manvityagi . Thanks !
