### ISSUE TITLE
Find problems/optimizations in existing code.

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#20]
The current code may have some things which can be improved, check out and raise any concerns you may notice.

**Comment by rohithmsr** [comment]
What about the initial project setup?
I have already asked for the issue #16 , so along with that I shall setup the project and work on #16 
@Manvityagi @abdus

**Comment by Manvityagi** [comment]
> What about the initial project setup?
> I have already asked for the issue #16 , so along with that I shall setup the project and work on #16
> @Manvityagi @abdus

Check the code, the initial project setup along with an API has been done

**Comment by Athira2199** [comment]
I think we can have a more formal documentation with swagger. If you too think it is a valid feature or enhancement, please assign it to me. I will add the initial documentation setup and each person can complete the documentation for their endpoint once they finish coding for that particular end-point. @Manvityagi
