### ISSUE TITLE
No need to use body-parser when using express version 4.16+

### ISSUE THREAD

**Issue by abhay27chauhan** [Girl-Code-It/Opportunity-Calendar-Backend#22]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Proposal

body-parser is been deprecated and Express version 4.16+, their own body-parser implementation is now included in the default Express package so there is no need for you to download another dependency.

You have added a line to your code that looks like the following:

- app.use(bodyparser.json());

If you are using Express 4.16+ you can now replace that line with:

- **app.use(express.json());**

You also have the following code in your environment:

- app.use(bodyParser.urlencoded({extended: true}));

You can replace that with:

- **app.use(express.urlencoded());**

**Comment by Manvityagi** [comment]
Wanna make a PR for the same? @abhay27chauhan

**Comment by rohithmsr** [comment]
@abhay27chauhan Check the code, the changes are made already and I have mentioned that in my PR.
@Manvityagi

**Comment by abhay27chauhan** [comment]
but there was no such issue open about this

**Comment by rohithmsr** [comment]
For issue #16 , I have also changed that single line of code (express.json())...If I had seen any issue open regarding this, I would have left that out intentionally(lol..I swear). But I guess you opened this issue only by today

**Comment by abhay27chauhan** [comment]
Ok bro 👍

**Comment by abhay27chauhan** [comment]
@rohithmsr bhai pls uninstall body parser also. Since we are not using it now

**Comment by rohithmsr** [comment]
@abhay27chauhan body-parser is still a dependency of express.

You will understand the history of body parser from this thread
https://github.com/expressjs/express/issues/2211

**Comment by abhay27chauhan** [comment]
read this article - 
https://medium.com/@mmajdanski/express-body-parser-and-why-may-not-need-it-335803cd048c
and 
https://dev.to/taylorbeeston/you-probably-don-t-need-body-parser-in-your-express-apps-3nio

It says there is no need for you to download another dependency, if you are using Express version 4.16+

@Manvityagi should i go ahead and uninstall the body-parser dependency

**Comment by Manvityagi** [comment]
> read this article -
> https://medium.com/@mmajdanski/express-body-parser-and-why-may-not-need-it-335803cd048c
> and
> https://dev.to/taylorbeeston/you-probably-don-t-need-body-parser-in-your-express-apps-3nio
> 
> It says there is no need for you to download another dependency, if you are using Express version 4.16+
> 
> @Manvityagi should i go ahead and uninstall the body-parser dependency

Go ahead @abhay27chauhan

**Comment by rohithmsr** [comment]
@abhay27chauhan Whenever you install express, it also installs body-parser since it is its dependency. 
 **The article which you have sent, only says that you need not install body-parser separately. It doesn't mean you need to uninstall.** 
Express automatically installs body-parser. 

It's good to remember that the body parsing was added, removed and then added again 
https://stackoverflow.com/questions/47232187/express-json-vs-bodyparser-json/47232318#47232318

@Manvityagi
