### ISSUE TITLE
Error in installation commands in README.md

### ISSUE THREAD

**Issue by Haneesha123** [Girl-Code-It/Opportunity-Calendar-Backend#25]
# Expected Behavior

In the install section of README.md, the command for starting the application is supposed to be `npm run start:dev`

# Current Behavior

By using `npm start`, we get the error `npm ERR! missing script: start`

Can I make a PR fixing this issue?

**Comment by Manvityagi** [comment]
Go ahead @Haneesha123

**Comment by Haneesha123** [comment]
@Manvityagi I have solved this issue. Please check PR #29
