### ISSUE TITLE
Add guidelines for GSSOC participants in Readme

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#27]
Similar to this [section](https://github.com/Girl-Code-It/Opportunity-Calendar-Frontend#guidelines-for-gssoc-participants), 
Add the same thing in readme after Technology Stack

Backend Channel on Discord:
 #opportunity-calendar-backtend

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by Manvityagi** [comment]
> Can I work on this issue under GSSoC'21? Kindly assign it to me.

Assigned, Go ahead @AshuKV

**Comment by Manvityagi** [comment]
What's the progress @ashuKV?

**Comment by AshuKV** [comment]
Hey @Manvityagi I am still working on it, will push the code by today.
