### ISSUE TITLE
Set-up project codebase

### ISSUE THREAD

**Issue by abdus** [Girl-Code-It/Opportunity-Calendar-Backend#3]
set-up the initial starter code. requirements: 

 - use `express`
 - use `mongodb`
 - use `typescript` 

for reference, you can [check this out](https://github.com/microsoft/TypeScript-Node-Starter)

**Comment by rohithmsr** [comment]
May I take this job?? @abdus 
I am a GSSOC'21 participant.

**Comment by abdus** [comment]
Sure. Feel free to drop me a message if you are stuck.

**Comment by rohithmsr** [comment]
Do I need to add Azure account and SendGrid account for this project? @abdus

**Comment by abdus** [comment]
Which Azure service you are planning to use and for what? 
We probably don't need SendGrid as emails from the frontend will be handled by Formspree. We will add it if required in the future.

**Comment by rohithmsr** [comment]
Should I use Azure for deployment? Or shall we take care of that later?
@abdus

**Comment by abdus** [comment]
Nope. Leave deployment part for now.
