### ISSUE TITLE
Add a Github action that automatically labels 'GSSOC21' to the newly created issue. 

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#30]
### **Feature request**:
Add a Github action that automatically labels 'GSSOC21'  for the newly created issue.

### **Is your feature request related to a problem? Please describe. (optional)**:
Adding labels is extra work for the maintainers, which can be avoided by GitHub action.

**Comment by priyanshu20** [comment]
I'd like to take this up
