### ISSUE TITLE
Google Login/Signup Strategy

### ISSUE THREAD

**Issue by ay2306** [Girl-Code-It/Opportunity-Calendar-Backend#33]
Subtask from issue #5

**Comment by ay2306** [comment]
I want to work on the issue, please assign it to me.

**Comment by Manvityagi** [comment]
> I want to work on the issue, please assign it to me.

Assigned @ay2306

**Comment by Kashish0423** [comment]
Hello @abdus  Sir @Manvityagi  mam, is there any work going on in this issue or can someone take it and get it done?

**Comment by jnv27** [comment]
@Kashish0423 I guess this issue is already assigned to someone and he is working on it
