### ISSUE TITLE
Github profile Links in the readme to open in a new tab

### ISSUE THREAD

**Issue by akshay1027** [Girl-Code-It/Opportunity-Calendar-Backend#45]
# Prerequisites

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Links in the readme to open in a new tab so that it is easier for the user to navigate to GitHub codebase.

**Comment by Manvityagi** [comment]
@akshay1027 Are you working on it?

**Comment by akshay1027** [comment]
I found out now that we cant do this on Github! I tried but it's not possible @Manvityagi ! here is the link to that: mojombo/github-flavored-markdown#28
so i will close this. Sorry.
