### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [Girl-Code-It/Opportunity-Calendar-Backend#46]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

Sever should run in cluster mode to run multiple instances of the server in fork mode to make it faster.

# Current Behavior

Server is currently running in a non cluster mode.

## Context

[Reason](https://www.w3schools.com/nodejs/ref_cluster.asp#:~:text=same%20server%20port.-,Node.,thread%2C%20to%20handle%20the%20load.)

[Module](https://www.npmjs.com/package/cluster)

I would like to work on this issue as a gssoc 21 participant.

**Comment by Shubham-Kumar-2000** [comment]
@Manvityagi  can you assign me this

**Comment by Manvityagi** [comment]
> @Manvityagi can you assign me this

Assigned @Shubham-Kumar-2000
