### ISSUE TITLE
Update the marking scheme of GSSOC in README.md

### ISSUE THREAD

**Issue by akshatvirmani** [Girl-Code-It/Opportunity-Calendar-Backend#51]
# Prerequisites

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

The marking scheme of GSSOC has been updated and the changes have not been updated in the README file of this project.

**Comment by akshatvirmani** [comment]
Kindly assign me this issue so I can make the required changes.

**Comment by Manvityagi** [comment]
Go ahead @akshatvirmani
