### ISSUE TITLE
Extract Swagger Schema into smaller files

### ISSUE THREAD

**Issue by abdus** [Girl-Code-It/Opportunity-Calendar-Backend#54]
### Expected Behavior

As of now, the schema in Swagger documentation blocks (written as JSDoc) contains a response schema. This can be extracted into a separate file, and reference whenever needed using `$ref`. There are two benefits of doing it. It will reduce the file size so that the file can be maintained easily. Second, It will allow us to reuse certain schema in more than one places.

### What needs to be done?

Extract the schema to a new file, preferably in `docs/ROUTE_FILE_NAME.json`(create if necessary). Then reference this file wherever required. For resources, please check Swagger docs (definitions, refs etc).

**Comment by Haneesha123** [comment]
@abdus I would like to work on this issue.

**Comment by abdus** [comment]
Sure.

**Comment by Haneesha123** [comment]
@abdus I need some clarity on this. You want me to replace schemas in GET and POST API documentation with $ref right? But schemas in GET and POST API differ slightly. But the properties are the same. Is it ok if I replace properties with $ref?

**Comment by abdus** [comment]
you don't have to merge both if they are not the same. just replace them with $ref.

**Comment by Manvityagi** [comment]
Any updates on this PR @Haneesha123. 
It has been quite a time as per the timelines.

CC: @abdus

**Comment by Haneesha123** [comment]
Sorry, I have been busy with exams. I will make the PR in a day.
