### ISSUE TITLE
Add the PATCH API for opportunities

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#57]
1. Add the PATCH API for opportunities 
2. Add corresponding documentation in `routes/opportunity.js` 
3. Add corresponding documentation in `documentation/APIS.md`

**Comment by Sukriti-sood** [comment]
@Manvityagi  I wanted to work upon

**Comment by Manvityagi** [comment]
Go ahead, 
Assigned to you.
