### ISSUE TITLE
Add onlyForFemale field in opportunities schema

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#58]
Add a boolean field onlyForFemale field in opportunities model, make it required and give default value false

**Comment by Sukriti-sood** [comment]
@Manvityagi  I wanted to work upon

**Comment by Sukriti-sood** [comment]
@Manvityagi Sorry , if I voilate any Rule.

**Comment by Manvityagi** [comment]
Please take care from next time @Sukriti-sood. 
You should not work on an issue and make a PR before getting it assigned to you.
