### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by shriya030** [Girl-Code-It/Opportunity-Calendar-Backend#6]
I am a GSSOC'21 participant and would like to add a feature in README.md where the contributors get automatically updated.
Can you please assign this issue to me?

**Comment by abdus** [comment]
How are you planning to add the contributors' list? Would it be updated automatically whenever a person contributes something to this repository? 
You can find a publicly accessible contributors list [here](https://github.com/Girl-Code-It/Opportunity-Calendar-Backend/graphs/contributors)

**Comment by shriya030** [comment]
Yes, it will be updated automatically. We can see, but it will enhance the readme. We can put the heading like our proud contributors and then display the pictures like this.
![image](https://user-images.githubusercontent.com/56861600/111037987-90ffdb80-844c-11eb-8ff8-21b3480efacf.png)

**Comment by abdus** [comment]
Alright. Go ahead and do this.
