### ISSUE TITLE
Add 'onlyForFemale' field in createOpportunity API

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#61]
In `controllers/opportunity/index.js` , `managers/opportunity/index.js` , `services/opportunity/index.js` , update the `createOpportunity` method to create the Opportunity with one more field `onlyForFemale`.

**Comment by ritik307** [comment]
@Manvityagi I would like to work on this issue .Plz assign it to me.
