### ISSUE TITLE
Add precommit Hook for code formatting

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#62]
The code should be automatically formatted while a commit is made. 

You may use this [resource](https://www.freecodecamp.org/news/how-to-add-commit-hooks-to-git-with-husky-to-automate-code-tasks/) for reference. 

There's a prettier config file in this repository. Use it to format code before commit. You can use [Husky and/or pretty-quick](https://prettier.io/docs/en/precommit.html#option-2-pretty-quickhttpsgithubcomazzpretty-quick) (if you want)

**Comment by Samridhi-98** [comment]
@Manvityagi  I would like to work on it will you please assign it to me.
