### ISSUE TITLE
Remove 'opportunity_id' field from models, APIs, Tests, Documentations

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#64]
The `opportunity_id` field is not needed, as we will be using the unique id generated by mongoose for tasks needing id.
It has to be removed from all the places in the project.

**Comment by jnv27** [comment]
Hey @Manvityagi ,I would like to work on this issue please assign it to me under Gssoc, 21

**Comment by Manvityagi** [comment]
> Hey @Manvityagi ,I would like to work on this issue please assign it to me under Gssoc, 21

Great, Assigned @jnv27

**Comment by jnv27** [comment]
![image](https://user-images.githubusercontent.com/44162351/115996822-81a0b000-a5fe-11eb-8328-bd28712b9b21.png)
I'm getting this message while merging, @Manvityagi is it fine? if not then what should i do to resolve it?

**Comment by jnv27** [comment]
> > Hey @Manvityagi ,I would like to work on this issue please assign it to me under Gssoc, 21
> 
> Great, Assigned @jnv27

I'm getting this error while merging, 
Error: your local changes to following files would be overwritten by merge.
Please commit your changes or stash them before you merge
Can you tell me how to resolve this? @Manvityagi

**Comment by Manvityagi** [comment]
> > > Hey @Manvityagi ,I would like to work on this issue please assign it to me under Gssoc, 21
> > 
> > 
> > Great, Assigned @jnv27
> 
> I'm getting this error while merging,
> Error: your local changes to following files would be overwritten by merge.
> Please commit your changes or stash them before you merge
> Can you tell me how to resolve this? @Manvityagi

Use `git stash` before merge and `git stash apply` after merge

**Comment by jnv27** [comment]
> > > > Hey @Manvityagi ,I would like to work on this issue please assign it to me under Gssoc, 21
> > > 
> > > 
> > > Great, Assigned @jnv27
> > 
> > 
> > I'm getting this error while merging,
> > Error: your local changes to following files would be overwritten by merge.
> > Please commit your changes or stash them before you merge
> > Can you tell me how to resolve this? @Manvityagi
> 
> Use `git stash` before merge and `git stash apply` after merge

@Manvityagi I have sent the PR after doing so, please merge it after checking.

**Comment by jnv27** [comment]
@Manvityagi  is there any problem with my PR because it has not been merged yet?
