### ISSUE TITLE
Add `organisationLogoURL` field in schema

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#65]
- `organisationLogoURL` field is to be added in the schema, 
- Don't keep it required, 
- Give default as - https://picsum.photos/200 
- Corresponding additions should be done in opportunity schema, APIS wherever required, swagger documentation, tests

**Comment by ritik307** [comment]
@Manvityagi I would like to work on this issue

**Comment by Manvityagi** [comment]
> @Manvityagi I would like to work on this issue

I will assign you once your previous PR is merged

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by Manvityagi** [comment]
> Can I work on this issue under GSSoC'21? Kindly assign it to me.

Hi @AshuKV, I have assigned to you, The frontend people are dependent on this issue for one of their PRs, Please keep this on priority and make a PR soon.

**Comment by Manvityagi** [comment]
It has been 3 days of inactivity on this PR, so I am unassigning you @AshuKV. 
Refer the [rules](https://github.com/Girl-Code-It/Opportunity-Calendar-Backend#rules) for clarifcation.

**Comment by AshuKV** [comment]
Can you pls tell how to resolve this error when I commit my code :
![1](https://user-images.githubusercontent.com/48694961/116461084-73b09080-a885-11eb-8a48-2fc032f66124.png)

**Comment by Kashish0423** [comment]
hello @Manvityagi mam , I would like to take this issue

**Comment by ritik307** [comment]
@Manvityagi I have already made a PR to a previous issue so kindly assign me this issue.

**Comment by Manvityagi** [comment]
> Can you pls tell how to resolve this error when I commit my code :
> ![1](https://user-images.githubusercontent.com/48694961/116461084-73b09080-a885-11eb-8a48-2fc032f66124.png)

I guess you haven't updated the tests properly @AshuKV

**Comment by abdus** [comment]
hey @AshuKV, you have to make PR for a `level-1` issue within two days. You have taken more than three days, and for the same reason, you were unassigned. So, I am going to assign it to the first person in the queue, i.e. @Kashish0423. 
@ritik307, I cannot assign this to you at the moment, as your previous PR has not been merged yet (which means you might have to make further changes).

**Comment by Manvityagi** [comment]
@Kashish0423 Please try to make the PR for the same asap, it is a priority issue.

**Comment by Kashish0423** [comment]
Okay mam , making a PR soon

**Comment by Kashish0423** [comment]
Hello @Manvityagi  mam, there is an issue with the test case as even npm test is giving compilation error ,so shall I make my PR without checking the tests or wait ? Also there is one more issue that , the onlyforFemale field is not added everywhere in the tests , I don't if it's left on purpose or shall be added ,
