### ISSUE TITLE
To Add No of issues/pull requests/forks/watchers/stars in Readme file

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#66]
It should be added at the top, just after the first title
Reference: https://shields.io/category/issue-tracking

**Comment by Samridhi-98** [comment]
@Manvityagi  I would like to work on it please assign it to me.

**Comment by Manvityagi** [comment]
> @Manvityagi I would like to work on it please assign it to me.

Can be assigned once your previous PR is merged

**Comment by Manvityagi** [comment]
Your other PR is merged @Samridhi-98, Wanna still take this one?

**Comment by Samridhi-98** [comment]
> Your other PR is merged @Samridhi-98, Wanna still take this one?

Yes
