### ISSUE TITLE
write test-case

### ISSUE THREAD

**Issue by abdus** [Girl-Code-It/Opportunity-Calendar-Backend#7]
Please add test cases to this project. You are free to use any test suite(Mocha, for example). Make sure the tests are written in TypeScript.

**Comment by rohithmsr** [comment]
May I take this job ??? @abdus .

**Comment by abdus** [comment]
hey @rohithmsr, if you are stuck, do let us know.

**Comment by rohithmsr** [comment]
Sure....Will make PR within tonight @abdus

**Comment by rohithmsr** [comment]
@abdus  Why do we want to write tests before code is developed?? In our case , the code isn't developed, so for what should we write testcases?

**Comment by Manvityagi** [comment]
@rohithmsr Will reopen it after getting some basic setup and APIs.
