### ISSUE TITLE
Update .travis.yml

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#73]
- Add mongdb in services
- Add script for running tests
- Replace `npm install` by `npm ci`

**Comment by jnv27** [comment]
@Manvityagi , I would like to work on this issue, and please check and merge my previous PR too on issue #64 .

**Comment by jnv27** [comment]
@Manvityagi I have a doubt, do I have to add only single script for running test like this "mocha ./tests/*/*" or I have to add scripts for each file in tests separately?

**Comment by Manvityagi** [comment]
> @Manvityagi I have a doubt, do I have to add only single script for running test like this "mocha ./tests/_/_" or I have to add scripts for each file in tests separately?

All test-files need not to be added separately @jnv27

**Comment by jnv27** [comment]
Hey @Manvityagi @abdus , I have sent the PR for this issue you can check and merge it.

**Comment by jnv27** [comment]
@Manvityagi @abdus , I sent my PR twice by making accurate changes but i don't know why it is showing conflicts in my PR, I'm new to open source can you help me resolve this problem?

**Comment by abdus** [comment]
you have to keep your fork updated with the main repository. I hope this helps: https://opensource.com/article/20/4/git-merge-conflict 
Let me know if you face any difficulties.
