### ISSUE TITLE
Create DELETE endpoint for opportunities

### ISSUE THREAD

**Issue by Vishal1003** [Girl-Code-It/Opportunity-Calendar-Backend#74]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Feature Request

I can see that there are apis for creating and fetching the opportunities but no api exists for updating and deleting.  @Manvityagi @abdus Kindly look into this issue and assign it to me if it makes sense.

**Comment by abdus** [comment]
upon merging PR #60, the 'Update' method will be available for use.

**Comment by abdus** [comment]
- Add the DELETE method for opportunities
- Add corresponding documentation in routes/opportunity.js
- Add corresponding documentation in documentation/APIS.md

**Comment by Vishal1003** [comment]
@abdus I would like to work on this issue. Kindly assign this to me?
