### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#78]
This [file](https://github.com/Girl-Code-It/Opportunity-Calendar-Backend/blob/develop/documentation/models.md) is not properly formatted. 
1. Format it properly 
2. Refer [this](https://github.com/Girl-Code-It/Opportunity-Calendar-Backend/tree/develop/models) and update the models.md file

**Comment by Samridhi-98** [comment]
@Manvityagi  I would like to work on it, please assign it to me.
Also, I have a doubt, Do I need to update the fields as mentioned in the `models folder` or redesign the `models.md` using html table?

**Comment by Manvityagi** [comment]
> @Manvityagi I would like to work on it, please assign it to me.
> Also, I have a doubt, Do I need to update the fields as mentioned in the `models folder` or redesign the `models.md` using html table?

You have to redesign the models.md file
