### ISSUE TITLE
Add ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#81]
You may refer [this](https://github.com/Girl-Code-It/Opportunity-Calendar-Frontend/tree/develop/.github/ISSUE_TEMPLATE)

**Comment by GuptaTanisha** [comment]
Please assign this to me.

**Comment by Manvityagi** [comment]
> Please assign this to me.

The deadline for Level-1 PR is 2 days @GuptaTanisha and it has been 3 days since it was assigned to you. Please provide an update.

**Comment by GuptaTanisha** [comment]
> > Please assign this to me.
> 
> The deadline for Level-1 PR is 2 days @GuptaTanisha and it has been 3 days since it was assigned to you. Please provide an update.

Please review the pull request.
