### ISSUE TITLE
Separate the logic of Pagination in Managers

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#89]
- Make a folder `helpers` in root dir, and move all the pagination logic in `managers/opportunity/index.js`  to a function in `helpers/pagination.js`, and use the function after importing in `managers/opportunity/index.js`. 
- The functionality of pagination should not be affected 
- This is being done to keep the code clean, modular, and maintainable

**Comment by Vishal1003** [comment]
@Manvityagi I would like to work on this!

**Comment by Manvityagi** [comment]
> @Manvityagi I would like to work on this!

Assigned @Vishal1003 :)
