### ISSUE TITLE
Add General Issue template in Issue Templates

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#96]
Like [this](https://github.com/Girl-Code-It/Opportunity-Calendar-Frontend/blob/develop/.github/ISSUE_TEMPLATE/general_issue.md)

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by Manvityagi** [comment]
> Can I work on this issue under GSSoC'21? Kindly assign it to me.

Assigned @AshuKV
